apiVersion: v1
kind: ConfigMap
metadata:
  name: machine-api-operator-images
  namespace: openshift-machine-api
data:
  images.json: '{"machineAPIOperator": "docker.io/openshift/origin-machine-api-operator:v4.0.0", "clusterAPIControllerAWS": "docker.io/openshift/origin-aws-machine-controllers:v4.0.0", "clusterAPIControllerOpenStack": "docker.io/openshift/origin-openstack-machine-controllers:v4.0.0", "clusterAPIControllerLibvirt": "docker.io/openshift/origin-libvirt-machine-controllers:v4.0.0", "clusterAPIControllerKubemark": "docker.io/gofed/kubemark-machine-controllers:v1.0", "clusterAPIControllerBaremetal": "quay.io/oglok/cluster-api-provider-baremetal@sha256:007b36754737d948bb88913de8cad49613f5e960176781944e04fee250f68b7a"}'
